---
title: "static_graphs"
author: "Timothy Lee"
date: "24/03/2020"
output: html_document
---

```{r}
library(readr)
library(tidyr)
library(dplyr)
library(stringr)
library(rvest)
library(purrr)
library(ggplot2)
```

```{r}
usage <- read_lines("data/gen8ou/gen8ou-0_usage.txt")
total_battles <- str_extract(usage[1], pattern = "[0-9]+")
total_battles
```

```{r}
#df_usage_colnames <- str_remove_all(usage[4], "[[:space:]]+") %>%
#  str_split(pattern = "\\|")

df_usage <- usage[6:(length(usage) - 1)] %>%
  data.frame(stringsAsFactors = FALSE) %>%
  separate(., col = ., sep = "\\|+", into = as.character(c(1:9))) %>%
  select(as.character(c(2:8)))


#Remove spaces in columns and percent signs
df_usage <- apply(df_usage, 2, str_remove_all, pattern = "[[:space:]]|%") %>%
  data.frame(stringsAsFactors = FALSE)

colnames(df_usage) <- c("Rank",
                        "Pokemon",
                        "Usage %",
                        "Raw",
                        "Raw %",
                        "Real",
                        "Real %")

df_usage$Rank <- as.integer(df_usage$Rank)
df_usage$`Usage %` <- as.double(df_usage$`Usage %`)
df_usage$Raw <- as.integer(df_usage$Raw)
df_usage$`Raw %` <- as.double(df_usage$`Raw %`)
df_usage$Real <- as.integer(df_usage$Real)
df_usage$`Real %` <- as.double(df_usage$`Real %`)

#df_usage
```

```{r}
# dex
df_dex <- read_html("Pokémon Pokédex_ list of Pokémon with stats _ Pokémon Database.html") %>%
  html_node(xpath = '//*[@id="pokedex"]') %>%
  html_table()

head(df_dex)
```

```{r}
# type df

df_type <- df_dex %>%
  select(Name, Type) %>%
  mutate(Name = str_replace_all(.data$Name, "Galarian.+", "-Galar")) %>%
  mutate(Name = str_replace_all(.data$Name, "Alolan.+", "-Alola")) %>%
  mutate(Name = str_replace_all(.data$Name, "Mega.+", "-Mega")) %>%
  mutate(Name = str_replace(.data$Name, "^-Mega", "Meganium")) %>%
  mutate(Name = str_remove_all(.data$Name, "Zen Mode|Standard Mode")) %>%
  mutate(Name = str_replace_all(.data$Name, "Eiscue.+", "Eiscue")) %>%
  mutate(Name = str_replace_all(.data$Name, " Rotom$", "")) %>%
  mutate(Name = str_replace_all(.data$Name, "Rotom", "Rotom-")) %>%
  mutate(Name = str_replace_all(.data$Name, "Rotom-$", "Rotom")) %>%
  mutate(Name = str_replace_all(.data$Name, "Morpeko.+", "Morpeko")) %>%
  mutate(Name = str_replace_all(.data$Name, "Basculin.+", "Basculin")) %>%
  mutate(Name = str_replace_all(.data$Name, "Aegislash.+", "Aegislash")) %>%
  mutate(Name = str_replace_all(.data$Name, "Toxtricity.+", "Toxtricity")) %>%
  mutate(Name = str_replace_all(.data$Name, " Kyurem$", "")) %>%
  mutate(Name = str_replace_all(.data$Name, "Kyurem", "Kyurem-")) %>%
  mutate(Name = str_replace_all(.data$Name, "Kyurem-$", "Kyurem")) %>%
  mutate(Name = str_replace_all(.data$Name, "IndeedeeMale", "Indeedee")) %>%
  mutate(Name = str_replace_all(.data$Name, "IndeedeeFemale", "Indeedee-F")) %>%
  mutate(Name = str_replace_all(.data$Name, "Keldeo.+", "Keldeo")) %>%
  mutate(Name = str_replace_all(.data$Name, "Mr\\. ", "Mr.\\")) %>%
  mutate(Name = str_replace_all(.data$Name, "Mime ", "Mime")) %>%
  mutate(Name = str_replace_all(.data$Name, "Type: Null", "Type:Null")) %>%
  distinct()


df_type$Name[8] <- "Charizard-Mega X"
df_type$Name[9] <- "Charizard-Mega Y"
df_type$Name[190] <- "Mewtwo-Mega X"
df_type$Name[191] <- "Mewtwo-Mega Y"

```

```{r}

df_usage_type <- left_join(df_usage, df_type, by = c("Pokemon" = "Name"))
head(df_usage_type)
```




```{r}
#NA check
x <- filter(df_usage_type, is.na(Type))
```

```{r}
types1 <- c("Grass",
           "Fire",
           "Water",
           "Electric",
           "Ground",
           "Rock",
           "Steel",
           "Flying",
           "Fighting",
           "Psychic",
           "Steel",
           "Bug",
           "Poison",
           "Dragon",
           "Ghost",
           "Dark",
           "Normal", 
           "Fairy",
           "Ice")
types2 <- c(types1, "")
types1_regex <- paste(types1, collapse = "|")
types2_regex <- paste(types2, collapse = "|")
types_regex_capture <- paste("(",
                             types1_regex,
                             ")",
                             "(",
                             types2_regex,
                             ")", sep = "", collapse = ""
                             )

df_usage_type2 <- extract(df_usage_type,
                          col = Type,
                          into = c("Type 1", "Type 2"),
                          types_regex_capture)
```

```{r}
#NA check
y <- filter(df_usage_type2, is.na(`Type 1`))
```

```{r}
df_usage_type_long <- pivot_longer(df_usage_type2,
                                   cols = c("Type 1", "Type 2"),
                                   names_to = "type_num",
                                   values_to = "Type") %>%
  filter(Type != "")
```

```{r}
df_usage_type_plot <- df_usage_type_long %>% 
  group_by(Type) %>%
  summarise(sum = sum(`Usage %`)) %>%
  arrange(Type)

x <- ggplot(df_usage_type_plot, aes(x = .data$sum, y = .data$Type, fill = Type)) +
  geom_col() + 
  theme_minimal() +
  labs(x = "Usage %", 
       y = "Type") +
  scale_fill_manual(values = c("#A6B91A", "#705746", "#6F35FC", "#F7D02C",
                               "#D685AD", "#C22E28", "#EE8130", "#A98FF3",
                               "#735797", "#7AC74C", "#E2BF65", "#96D9D6",
                               "#A8A77A", "#A33EA1", "#F95587", "#B6A136",
                               "#B7B7CE", "#6390F0"
                               )
                    ) +
  theme(legend.position = "none")

x
  
```

```{r}
DT::datatable(df_usage_type2)
```

